
package skipfish_gui;

import java.awt.Component;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.parser.Element;

/**
 *
 * @author Isaac
 */
public class Skipfish_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Skipfish_Frame
     */
    public Skipfish_Frame() {
        initComponents();
        
        jTextPane2.addHyperlinkListener( new HyperlinkListener(){
            @Override
            public void hyperlinkUpdate(HyperlinkEvent e) {
                if(e.getEventType() == HyperlinkEvent.EventType.ACTIVATED)
                    if(Desktop.isDesktopSupported())
                        try {
                            Desktop.getDesktop().browse(e.getURL().toURI());
                        } catch (IOException | URISyntaxException ex) {
                           
                        }
            }
        } );
        console = (HTMLDocument)this.jTextPane2.getStyledDocument();
        
        
        this.initilizeThread();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(6, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(6, 32767));
        jTextField1 = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 5), new java.awt.Dimension(73, 0), new java.awt.Dimension(5, 32767));
        jTextField2 = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jLabel3 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(0, 32767));
        jTextField3 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(8, 0), new java.awt.Dimension(8, 32767));
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(10, 32767));
        jTextField4 = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(22, 32767));
        jButton1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(49, 0), new java.awt.Dimension(46, 32767));
        jTextField5 = new javax.swing.JTextField();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(32, 32767));
        jTextField6 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel15 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jCheckBox5 = new javax.swing.JCheckBox();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jTextField8 = new javax.swing.JTextField();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        jPanel16 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jPanel17 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        jTextField7 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        filler20 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));

        jFileChooser1.setDialogTitle("Set project directory");
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        jFileChooser2.setAcceptAllFileFilterUsed(false);
        jFileChooser2.setApproveButtonText("Select");
        jFileChooser2.setFileFilter(new FileNameExtensionFilter("Dictionary files", "wl"));

        jFrame1.setSize(new java.awt.Dimension(500, 700));
        jFrame1.getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanel19.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.PAGE_AXIS));

        jScrollPane3.setMinimumSize(new java.awt.Dimension(26, 250));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(162, 306));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(200);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea2.setRows(10);
        jTextArea2.setMaximumSize(new java.awt.Dimension(2147483647, 32767));
        jTextArea2.setMinimumSize(new java.awt.Dimension(0, 250));
        jScrollPane3.setViewportView(jTextArea2);

        jPanel19.add(jScrollPane3);
        jPanel19.add(filler21);

        jTextPane2.setEditable(false);
        jTextPane2.setContentType("text/html"); // NOI18N
        jTextPane2.setText("<html>\n  <head>\n\n  </head>\n\n  <body >\n\n<div id=\"console-id\" style=\"font-family:Monospace; font-weight:bold\">\n\n\n\n</div>\n  </body>\n\n</html>\n");
        jTextPane2.setMinimumSize(new java.awt.Dimension(6, 300));
        jTextPane2.setPreferredSize(new java.awt.Dimension(6, 300));
        jScrollPane2.setViewportView(jTextPane2);

        jPanel19.add(jScrollPane2);

        jFrame1.getContentPane().add(jPanel19);

        jMenuItem1.setAction(new javax.swing.text.DefaultEditorKit.PasteAction());
        jMenuItem1.setText("Paste");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setAction(new javax.swing.text.DefaultEditorKit.CopyAction());
        jMenuItem2.setText("Copy");
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setAction(new javax.swing.text.DefaultEditorKit.CutAction());
        jMenuItem3.setText("Cut");
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setPreferredSize(new java.awt.Dimension((int)java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getWidth()/2+250, (int)java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDisplayMode().getHeight() - 80));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Administration"));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(515, 120));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 0, 10));

        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel3.setMinimumSize(new java.awt.Dimension(199, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(503, 40));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Default directory");
        jPanel3.add(jLabel1);
        jPanel3.add(filler5);

        jTextField1.setEditable(false);
        jTextField1.setText(System.getProperty("user.dir"));
        jTextField1.setMaximumSize(new java.awt.Dimension(2147483647, 35));
        jTextField1.setMinimumSize(new java.awt.Dimension(6, 35));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 35));
        jPanel3.add(jTextField1);
        jPanel3.add(filler6);

        jButton2.setText("Change");
        jButton2.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3);

        jPanel6.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel6.setMinimumSize(new java.awt.Dimension(220, 40));
        jPanel6.setPreferredSize(new java.awt.Dimension(293, 40));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Scan ID");
        jPanel6.add(jLabel2);
        jPanel6.add(filler2);

        jTextField2.setEditable(false);
        jTextField2.setText(String.valueOf((int)(Math.random()*1000+1)).concat("0000").substring(0, 4)
        );
        jTextField2.setComponentPopupMenu(jPopupMenu1);
        jTextField2.setMaximumSize(new java.awt.Dimension(100, 35));
        jTextField2.setMinimumSize(new java.awt.Dimension(70, 35));
        jTextField2.setName(""); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(70, 35));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jPanel6.add(jTextField2);
        jPanel6.add(filler3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("-");
        jPanel6.add(jLabel3);
        jPanel6.add(filler4);

        jTextField3.setToolTipText("");
        jTextField3.setMaximumSize(new java.awt.Dimension(2147483647, 35));
        jTextField3.setMinimumSize(new java.awt.Dimension(6, 35));
        jTextField3.setPreferredSize(new java.awt.Dimension(6, 35));
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jPanel6.add(jTextField3);
        jPanel6.add(filler1);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBox1.setText("Custom ID");
        jCheckBox1.setMaximumSize(new java.awt.Dimension(90, 30));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(90, 30));
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jPanel6.add(jCheckBox1);

        jButton9.setText("New ID");
        jButton9.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton9.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });
        jPanel6.add(jButton9);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dictionaries"));
        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 160));
        jPanel5.setPreferredSize(new java.awt.Dimension(223, 160));
        jPanel5.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        jPanel4.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Results directory");
        jLabel4.setMaximumSize(new java.awt.Dimension(120, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(104, 20));
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 20));
        jPanel4.add(jLabel4);
        jPanel4.add(filler7);

        jTextField4.setEditable(false);
        jTextField4.setToolTipText("");
        jTextField4.setMaximumSize(new java.awt.Dimension(2147483647, 35));
        jTextField4.setPreferredSize(new java.awt.Dimension(6, 35));
        jPanel4.add(jTextField4);
        jPanel4.add(filler8);

        jButton1.setText("Change");
        jButton1.setToolTipText("");
        jButton1.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(60, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel5.add(jPanel4);

        jPanel9.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Learned words");
        jPanel9.add(jLabel5);
        jPanel9.add(filler9);

        jTextField5.setEditable(false);
        jTextField5.setMaximumSize(new java.awt.Dimension(2147483647, 35));
        jTextField5.setPreferredSize(new java.awt.Dimension(6, 35));
        jPanel9.add(jTextField5);
        jPanel9.add(filler10);

        jButton3.setText("Change");
        jButton3.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jPanel9.add(jButton3);

        jPanel5.add(jPanel9);

        jPanel10.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Input dictionary ");
        jPanel10.add(jLabel6);
        jPanel10.add(filler11);

        jTextField6.setEditable(false);
        jTextField6.setText(System.getProperty("user.dir") + "/dictionaries/complete.wl");
        jTextField6.setMaximumSize(new java.awt.Dimension(2147483647, 35));
        jTextField6.setPreferredSize(new java.awt.Dimension(6, 35));
        jPanel10.add(jTextField6);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Enable");
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });
        jPanel10.add(jCheckBox2);
        jPanel10.add(filler12);

        jButton4.setText("Change");
        jButton4.setMaximumSize(new java.awt.Dimension(90, 30));
        jButton4.setName(""); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        jPanel10.add(jButton4);

        jPanel5.add(jPanel10);

        jPanel1.add(jPanel5);

        jPanel7.setMinimumSize(new java.awt.Dimension(174, 300));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Authentication"));
        jPanel11.setMinimumSize(new java.awt.Dimension(174, 200));
        jPanel11.setPreferredSize(new java.awt.Dimension(300, 73));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jCheckBox4.setText("Cookies (name1:value1;name2:value2;name3:value3...)");
        jCheckBox4.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        jCheckBox4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox4StateChanged(evt);
            }
        });
        jPanel8.add(jCheckBox4);

        jPanel11.add(jPanel8);
        jPanel11.add(filler19);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.Y_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(166, 70));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setComponentPopupMenu(jPopupMenu1);
        jTextArea1.setEnabled(false);
        jTextArea1.setMinimumSize(new java.awt.Dimension(4, 50));
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel14.add(jScrollPane1);

        jPanel11.add(jPanel14);
        jPanel11.add(filler16);

        jPanel15.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jPanel15.setMinimumSize(new java.awt.Dimension(162, 40));
        jPanel15.setPreferredSize(new java.awt.Dimension(631, 40));
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jCheckBox3.setText("Reject new cookies");
        jPanel15.add(jCheckBox3);
        jPanel15.add(filler17);

        jCheckBox5.setText("Authentication Header (name:value):");
        jCheckBox5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox5StateChanged(evt);
            }
        });
        jPanel15.add(jCheckBox5);
        jPanel15.add(filler18);

        jTextField8.setEnabled(false);
        jPanel15.add(jTextField8);

        jPanel11.add(jPanel15);
        jPanel11.add(filler15);

        jPanel7.add(jPanel11);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Performance"));
        jPanel16.setMaximumSize(new java.awt.Dimension(32839, 80));
        jPanel16.setPreferredSize(new java.awt.Dimension(423, 80));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jPanel18.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel18.setMinimumSize(new java.awt.Dimension(550, 51));
        jPanel18.setPreferredSize(new java.awt.Dimension(550, 51));
        jPanel18.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        jCheckBox8.setText("No binary docs in RAM");
        jPanel18.add(jCheckBox8);

        jCheckBox6.setText("No extension guessing");
        jPanel18.add(jCheckBox6);

        jCheckBox9.setText("Max requests per second");
        jCheckBox9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jCheckBox9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jCheckBox9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox9StateChanged(evt);
            }
        });
        jPanel18.add(jCheckBox9);

        jCheckBox10.setText("Do not submit forms");
        jPanel18.add(jCheckBox10);

        jCheckBox7.setText("Flush request/response data to disk");
        jPanel18.add(jCheckBox7);

        jPanel16.add(jPanel18);

        jPanel17.setMaximumSize(new java.awt.Dimension(60, 80));
        jPanel17.setMinimumSize(new java.awt.Dimension(60, 80));
        jPanel17.setPreferredSize(new java.awt.Dimension(60, 80));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.PAGE_AXIS));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));
        jSpinner1.setEnabled(false);
        jSpinner1.setMaximumSize(new java.awt.Dimension(60, 35));
        jSpinner1.setMinimumSize(new java.awt.Dimension(60, 35));
        jSpinner1.setPreferredSize(new java.awt.Dimension(60, 35));
        jPanel17.add(jSpinner1);

        jPanel16.add(jPanel17);

        jPanel7.add(jPanel16);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Site"));
        jPanel12.setMaximumSize(new java.awt.Dimension(2147483647, 80));
        jPanel12.setMinimumSize(new java.awt.Dimension(75, 80));
        jPanel12.setPreferredSize(new java.awt.Dimension(159, 80));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("URL");
        jPanel12.add(jLabel7);
        jPanel12.add(filler13);

        jTextField7.setComponentPopupMenu(jPopupMenu1);
        jTextField7.setMaximumSize(new java.awt.Dimension(2147483647, 35));
        jTextField7.setPreferredSize(new java.awt.Dimension(6, 35));
        jPanel12.add(jTextField7);

        jPanel7.add(jPanel12);

        jPanel13.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel13.setMinimumSize(new java.awt.Dimension(75, 40));
        jPanel13.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel13.setLayout(new java.awt.GridLayout(1, 5, 20, 10));
        jPanel13.add(filler14);

        jButton6.setText("Stop Scanner");
        jButton6.setEnabled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });
        jPanel13.add(jButton6);

        jButton7.setText("Show cmd line");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });
        jPanel13.add(jButton7);

        jButton8.setText("Run");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton8MouseReleased(evt);
            }
        });
        jPanel13.add(jButton8);
        jPanel13.add(filler20);

        jPanel7.add(jPanel13);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        
        if (!this.jButton2.isEnabled()) return;
        
        String directory = jTextField1.getText();
        if(this.jFileChooser1.showOpenDialog(jPanel1) == JFileChooser.APPROVE_OPTION)
            directory= jFileChooser1.getSelectedFile().toString();
        this.jTextField1.setText(directory);
    }//GEN-LAST:event_jButton2MouseReleased

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
       
        this.jTextField2.setEditable(this.jCheckBox1.isSelected());
        this.jTextField2.requestFocus();
        
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        
        if (!this.jButton9.isEnabled()) return;
        
        this.jTextField2.setText(String.valueOf((int)(Math.random()*1000+1)).concat("0000").substring(0, 4));
        this.jTextField3.requestFocus();
        
    }//GEN-LAST:event_jButton9MouseReleased

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        
        this.jTextField3.setText(this.jTextField3.getText().replaceAll("\\W", ""));
        
        if(!this.jTextField3.getText().isEmpty()){
        String outputDir = new File(this.jTextField1.getText() + "/" +
                this.jTextField2.getText() + "-" + this.jTextField3.getText() + this.RESULTS).getAbsolutePath();
        String outputDic = new File(this.jTextField1.getText() + "/" +
                this.jTextField2.getText() + "-" + this.jTextField3.getText() + this.LEARNED).getAbsolutePath();
        
        this.jTextField4.setText(outputDir);
        this.jTextField5.setText(outputDic);
        this.outputfile = ".wl";
        this.outputfile = this.jTextField2.getText() + "-" + this.jTextField3.getText() + this.outputfile;
        }
        
    }//GEN-LAST:event_jTextField3FocusLost

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        
        if (!this.jButton1.isEnabled()) return;
        
        String directory = jTextField4.getText();
        if(this.jFileChooser1.showOpenDialog(jPanel1) == JFileChooser.APPROVE_OPTION)
            directory= jFileChooser1.getSelectedFile().toString();
        this.jTextField4.setText(directory);
        
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        
        if (!this.jButton3.isEnabled()) return;
        
        String directory = jTextField5.getText();
        if(this.jFileChooser1.showOpenDialog(jPanel1) == JFileChooser.APPROVE_OPTION)
            directory= jFileChooser1.getSelectedFile().toString();
        this.jTextField5.setText(directory);
        
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        
        if (!this.jButton4.isEnabled()) return;

        String directory = jTextField6.getText();
        if(this.jFileChooser2.showOpenDialog(jPanel1) == JFileChooser.APPROVE_OPTION)
            directory= jFileChooser2.getSelectedFile().toString();
        this.jTextField6.setText(directory);
        
    }//GEN-LAST:event_jButton4MouseReleased

    private void jCheckBox4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox4StateChanged
        
        this.jTextArea1.setEnabled(this.jCheckBox4.isSelected());
        this.jTextArea1.requestFocus();
        
    }//GEN-LAST:event_jCheckBox4StateChanged

    private void jCheckBox5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox5StateChanged
        
        this.jTextField8.setEnabled(this.jCheckBox5.isSelected());
        this.jTextField8.requestFocus();
        
    }//GEN-LAST:event_jCheckBox5StateChanged

    private void jCheckBox9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox9StateChanged
        
        this.jSpinner1.setEnabled(this.jCheckBox9.isSelected());
        this.jSpinner1.requestFocus();
        
    }//GEN-LAST:event_jCheckBox9StateChanged

    private void jTextArea1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusLost
        
        this.cookies = this.jTextArea1.getText();
        boolean formatFollowed = cookies.matches("[\\S:\\S;]+");
        
        if(formatFollowed && !this.jTextArea1.getText().isEmpty())
        {
            this.cookies = this.cookies.replace(":", "=");
            this.cookies = this.cookies.substring(0, this.cookies.length() - 1);
            this.cookies = this.cookies.replace(";", "' -C '");
            
        }
        else if(!this.jTextArea1.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Please follow the format for all your cookies.");
        
    }//GEN-LAST:event_jTextArea1FocusLost

    private void jButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseReleased
       
        if (!this.jButton8.isEnabled()) return;

    
        if( !new File(this.jTextField4.getText()+"/index.html").isFile())
        {
            if(this.vallidateInput() && this.isValidURL(this.jTextField7.getText().trim()))
            {
                if(new File(this.jTextField6.getText()).isFile() || !this.jCheckBox2.isSelected())
                {
                    this.jButton8.setEnabled(false);
                    this.recursivelyDisableComponents(this.jPanel2, false);
                    this.recursivelyDisableComponents(this.jPanel5, false);
                    
                    String[] cmds = this.getAllCommands(os.substring(0, 3).toLowerCase());
                    
                    this.jTextArea2.setRows(this.jTextArea2.getRows() + 10);
                    this.jTextArea2.append(this.jTextField2.getText() + "-"+this.jTextField3.getText() + "\n");
                    this.jTextArea2.append(cmds[0] + "\n\n" + cmds[1] + "\n\n" + cmds[2] 
                            + "\n\n" + cmds[3] + "\n\n");
                    
                    switch(os.substring(0, 3).toLowerCase())
                    {
                        case "win":
                            commandArray = new String[]{"cmd.exe", "/c", cmds[0] +
                                    " & "+ cmds[1]+" & "+ cmds[2] +" & "+ cmds[3]};
                            break;
                        case "lin":
                            commandArray = new String[]{"bash", "-c", cmds[0] +
                                    " ; "+ cmds[1]+" ; "+ cmds[2] +" ; "+ cmds[3]};
                            break;
                        case "mac":
                            commandArray = new String[]{"bash", "-c", cmds[0] +
                                    " ; "+ cmds[1]+" ; "+ cmds[2] +" ; "+ cmds[3]};
                            break;
                        case "bsd":
                            break;
                    }      
                    JOptionPane.showMessageDialog(null,"Starting scanner, please stand by...");
                    
                    this.initilizeThread();
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Skipfish_Frame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    stopped = false;
                    scanner.start();
                    
                }
                else if(this.jCheckBox2.isSelected())
                    JOptionPane.showMessageDialog(null, "Please, either provide a valid "
                            + "Input Dictionary or disable the option.");
            }
            else if(!this.vallidateInput())
                JOptionPane.showMessageDialog(null, "Please fill all the required fields.");
            else
                JOptionPane.showMessageDialog(null, "Please doble check the URL");
        }
        else if(JOptionPane.showConfirmDialog(this,"There is a report with this "
                + "name and ID already! Do you want to change the ID?") == JOptionPane.OK_OPTION)
        {
            jTextField2.setText(String.valueOf((int)(Math.random()*1000+1)).concat("0000").substring(0, 4));
            this.jTextField3.requestFocus();
        }
        else
            JOptionPane.showMessageDialog(null, "OK, then change the path manually before pressing the \"Run\" button.");
        
            
    }//GEN-LAST:event_jButton8MouseReleased

    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
        
        this.jFrame1.setVisible(true);
       
        
    }//GEN-LAST:event_jButton7MouseReleased

    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased
        
        if (!this.jButton6.isEnabled()) return;
        
        if(JOptionPane.showConfirmDialog(this,"Are you sure you want to interrupt Skipfish?") == JOptionPane.OK_OPTION)
        {
            this.jButton6.setEnabled(false);
            this.stopped = true;

            ProcessBuilder processBuilder = new ProcessBuilder();
            String[] cancelScanner = {"","",""};
            switch(os.substring(0, 3).toLowerCase())
            {
                case "win":
                    cancelScanner = new String[]{"cmd.exe", "/c", "taskkill /PID " + this.PID};
                    break;
                case "lin":
                    cancelScanner = new String[]{"bash", "-c", "kill -2 " + this.PID};
                    break;
                case "mac":
                    cancelScanner = new String[]{"bash", "-c", "kill -2 " + this.PID};
                    break;
                case "bsd":
                    break;
            }
            
            processBuilder.command(cancelScanner[0], cancelScanner[1], cancelScanner[2]);
            try {
                processBuilder.start();
                JOptionPane.showMessageDialog(null,"Skipfish has stopped, saving your report...");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Operative System not supported... yet");
            }
            
              
            
        }
    }//GEN-LAST:event_jButton6MouseReleased

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        
        this.jTextField2.setText(this.jTextField2.getText().replaceAll("\\D", ""));
        this.jTextField3.requestFocus();
        
    }//GEN-LAST:event_jTextField2FocusLost

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        
        this.jTextField6.setEnabled(this.jCheckBox2.isSelected());
        this.jButton4.setEnabled(this.jCheckBox2.isSelected());
        
    }//GEN-LAST:event_jCheckBox2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Skipfish_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Skipfish_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Skipfish_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Skipfish_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Skipfish_Frame().setVisible(true);
            }
        });
    }
    
    private void appendToPane(String s)
    {
        try {
            console.insertBeforeEnd(console.getElement("console-id"), s);
        } catch (BadLocationException | IOException ex) {
            Logger.getLogger(Skipfish_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void recursivelyDisableComponents(JComponent comp, boolean disEn)
    {
        synchronized(comp.getTreeLock()) {
            if(comp.getComponentCount() > 1)
                for (Component c : comp.getComponents())
                {
                    c.setEnabled(disEn);
                    this.recursivelyDisableComponents((JComponent)c, disEn);
                }
        }
        
    }
    
    public void initilizeThread()
    {
        scanner = new Thread(new Runnable(){
            @Override
            public void run()
            {

                ProcessBuilder processBuilder = new ProcessBuilder();
                processBuilder.command(commandArray[0], commandArray[1], commandArray[2]);
                try
                {
                    skipfish = processBuilder.start();
                    
                    
                    BufferedReader reader = new BufferedReader(
                    new InputStreamReader( skipfish.getInputStream() ) );

                    String line;
                    while( (line = reader.readLine() ) != null )
                    {
                        if(!stopped)
                        {
                            
                            if(line.equals("\n"))
                                appendToPane("<br>");
                            else
                                appendToPane("<p>" + line + "</p>");
                            if(line.contains("PID:"))
                            {
                                PID = line.substring(line.indexOf("PID: ") );
                                PID = PID.replaceAll("\\D", "");
                                jButton6.setEnabled(true);
                            }
                        }
                    }
                    
                    appendToPane("<br><br><b>You may see the reports here: </b>"
                            + "<ul style=\"list-style-type:disc;\">");
                    reports.add("<li><a href=\"" + new File(jTextField4.getText()).toURI().toURL() + 
                        "index.html" + "\">" + jTextField2.getText()+ "-" + 
                        jTextField3.getText() + "</a></li>");
                    for(String report: reports)
                        appendToPane(report);
                    appendToPane("</ul><br><br>");   

                        JOptionPane.showMessageDialog(null, "Skipfish finished! You may now see the report.");
                        jTextPane2.setCaretPosition(console.getLength());
                }
                catch (IOException ex){
                    JOptionPane.showMessageDialog(null,ex.getMessage());
                }
                
                jFrame1.setVisible(true);
                jTextPane2.requestFocus();
                jButton8.setEnabled(true);
                jButton6.setEnabled(false);
                
                recursivelyDisableComponents(jPanel2, true);
                recursivelyDisableComponents(jPanel5, true);

            }


        });
    }
    
    private boolean vallidateInput()
    {
        return !this.jTextField1.getText().isEmpty() && !this.jTextField2.getText().isEmpty() &&
                !this.jTextField3.getText().isEmpty() &&
                !this.jTextField4.getText().isEmpty() &&
                !this.jTextField5.getText().isEmpty() &&
                !this.jTextField6.getText().isEmpty() &&
                !this.jTextField7.getText().isEmpty();
    }
    
    private boolean isValidURL(String urlStr) {
        try {
            new URL(urlStr);
          return true;
        }
        catch (MalformedURLException e) {
            return false;
        }
    }
    
    private String[] getAllCommands(String os)
    {
        String[] commands = new String [4];
        String mkdirAux = "";
        
        mkdirCommand = "mkdir ";
        touchCommand = "touch ";
        mainCommand = "skipfish ";
        
        switch(os)
        {
            case "win":
                mkdirAux = this.mkdirCommand + this.jTextField5.getText();
                this.mkdirCommand = this.mkdirCommand + this.jTextField4.getText();
                this.touchCommand = this.touchCommand.replace("touch", "type nul >>") + 
                        this.jTextField5.getText() + "/"+ this.outputfile;
                
                break;
            case "lin":
                mkdirAux = this.mkdirCommand + "-p " + this.jTextField5.getText();
                this.mkdirCommand = this.mkdirCommand + "-p " + this.jTextField4.getText();
                this.touchCommand = this.touchCommand + this.jTextField5.getText() + "/"+ this.outputfile;
                
                break;
            case "mac":
                mkdirAux = this.mkdirCommand + "-p " + this.jTextField5.getText();
                this.mkdirCommand = this.mkdirCommand + "-p " + this.jTextField4.getText();
                this.touchCommand = this.touchCommand + this.jTextField5.getText() + "/"+ this.outputfile;
                break;
            case "bsd":
                break;
        }
        this.getMainCommand();
        
        commands[0] = this.mkdirCommand;
        commands[1] = mkdirAux;
        commands[2] = this.touchCommand;
        commands[3] = this.mainCommand;
        
        return commands;
    }
    
    public void getMainCommand()
    {
        this.mainCommand = this.mainCommand.concat("-o '" + this.jTextField4.getText() + "' " );
        this.mainCommand = this.mainCommand.concat("-W '" + this.jTextField5.getText() + "/" +this.outputfile + "' ");
        
        if( this.jCheckBox2.isSelected() )
            this.mainCommand = this.mainCommand.concat("-S '" + this.jTextField6.getText() + "' ");
        
        if( this.jCheckBox3.isSelected() )
            this.mainCommand = this.mainCommand.concat("-N ");
        
        if( this.jCheckBox4.isSelected() )
            this.mainCommand = this.mainCommand.concat( "-C '" + this.cookies + "' ");
        
        if( this.jCheckBox5.isSelected() )
            this.mainCommand = this.mainCommand.concat( "-H " + this.jTextField8.getText().replaceFirst(":", "=") + " ");
        
        if( this.jCheckBox6.isSelected() )
            this.mainCommand = this.mainCommand.concat("-Y ");
        
        if( this.jCheckBox7.isSelected() )
            this.mainCommand = this.mainCommand.concat("--flush-to-disk ");
        
        if( this.jCheckBox8.isSelected() )
            this.mainCommand = this.mainCommand.concat("-e ");
        
        if( this.jCheckBox9.isSelected() )
            this.mainCommand = this.mainCommand.concat("-l " + this.jSpinner1.getValue().toString() + " ");
        
        if( this.jCheckBox10.isSelected() )
            this.mainCommand = this.mainCommand.concat("-O ");

        this.mainCommand = this.mainCommand.concat(this.jTextField7.getText());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler20;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
    
    private final String RESULTS = "/Results";
    private final String LEARNED = "/LearnedWords";
    private String outputfile = "newWords.wl";
    private String mkdirCommand = "mkdir ";
    private String touchCommand = "touch ";
    private String mainCommand = "skipfish ";
    private String commandArray[];
    private String cookies = "";
    private final String os = System.getProperty("os.name");
    private Process skipfish;
    private Thread scanner;
    private HTMLDocument console;
    private String PID;
    private boolean stopped = false;
    private List<String> reports = new ArrayList<>();
    
}
